[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
graphene = "3yErVeGSU3LHZzTnKjkoV5fPkcFQxyjeroLRo5VtSvEf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test ./tests/"
