/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Direction of encryption (affects key derivation for domain separation). */
export const enum EncryptionDirection {
  /** User encrypting input/code for worker */
  Input = 0,
  /** Worker encrypting result for user */
  Output = 1
}
/**
 * Derive channel keys from Ed25519 identities and a shared channel identifier.
 *
 * Both parties will derive the same master key.
 */
export declare function deriveChannelKeys(localSecret: Buffer, peerPubkey: Buffer, channelId: Buffer): ChannelKeys
/**
 * Encrypt data for a job using channel keys.
 *
 * Uses XChaCha20-Poly1305 with per-job ephemeral keys for forward secrecy.
 */
export declare function encryptJobBlob(plaintext: Buffer, channelKeys: ChannelKeys, jobId: string, direction: EncryptionDirection): EncryptedBlob
/**
 * Decrypt a job blob using channel keys.
 */
export declare function decryptJobBlob(encrypted: EncryptedBlob, channelKeys: ChannelKeys, jobId: string, direction: EncryptionDirection): Buffer
/**
 * Compute the BLAKE3 hash of the given data.
 *
 * Returns the 32-byte hash as a Buffer.
 */
export declare function blake3Hash(data: Buffer): Buffer
/** An egress rule specifying an allowed outbound connection. */
export interface EgressRule {
  /** Hostname or IP address. */
  host: string
  /** Port number. */
  port: number
  /** Protocol (tcp/udp). */
  protocol: string
}
/** Resource usage metrics for a completed job. */
export interface JobMetrics {
  /** Peak memory usage in bytes. */
  peakMemoryBytes: bigint
  /** Total CPU time in milliseconds. */
  cpuTimeMs: bigint
  /** Total network bytes received. */
  networkRxBytes: bigint
  /** Total network bytes transmitted. */
  networkTxBytes: bigint
}
/** Status of a job. */
export const enum JobStatus {
  /** Job accepted and queued for execution. */
  Accepted = 'Accepted',
  /** Job is currently running. */
  Running = 'Running',
  /** Job completed successfully (exit code 0). */
  Succeeded = 'Succeeded',
  /** Job failed (non-zero exit code). */
  Failed = 'Failed',
  /** Job exceeded time limit. */
  Timeout = 'Timeout',
  /** Job was rejected (check reject_reason field). */
  Rejected = 'Rejected'
}
/** Reason for job rejection. */
export const enum RejectReason {
  /** Worker is at capacity. */
  CapacityFull = 'CapacityFull',
  /** Requested kernel is not supported. */
  UnsupportedRuntime = 'UnsupportedRuntime',
  /** Requested resources exceed worker limits. */
  ResourcesExceedLimits = 'ResourcesExceedLimits',
  /** Environment variables total size exceeds limit. */
  EnvTooLarge = 'EnvTooLarge',
  /** Environment variable name is invalid. */
  InvalidEnvName = 'InvalidEnvName',
  /** Environment variable uses reserved GRAPHENE_* prefix. */
  ReservedEnvPrefix = 'ReservedEnvPrefix',
  /** Code or input blob could not be fetched. */
  AssetUnavailable = 'AssetUnavailable',
  /** Inline asset exceeds maximum allowed size. */
  InlineTooLarge = 'InlineTooLarge',
  /** Generic internal error. */
  InternalError = 'InternalError'
}
/** Configuration for creating a Graphene client. */
export interface ClientConfig {
  /** Worker HTTP URL (e.g., "http://192.168.1.100:3000"). */
  workerUrl: string
  /** Your Ed25519 secret key (32 bytes). */
  secretKey: Buffer
  /** Shared channel identifier (32 bytes) - used for key derivation. */
  channelId: Buffer
  /** Worker's Ed25519 public key (hex-encoded, 64 hex chars). */
  workerPubkey: string
}
/** Resource requirements for a job. */
export interface ResourceOptions {
  /** Number of vCPUs (default: 1). */
  vcpu?: number
  /** Memory in MB (default: 256). */
  memoryMb?: number
}
/** Networking options for a job. */
export interface NetworkingOptions {
  /** Estimated network ingress in megabytes. */
  estimatedIngressMb?: bigint
  /** Estimated network egress in megabytes. */
  estimatedEgressMb?: bigint
  /** Egress allowlist. */
  egressAllowlist?: Array<EgressRule>
}
/** Asset delivery options for a job. */
export interface AssetOptions {
  /** Enable zstd compression before encryption. */
  compress?: boolean
}
/** Options for submitting a job. */
export interface JobOptions {
  /** Code to execute (UTF-8 string). */
  code: string
  /** Optional input data. */
  input?: Buffer
  /** Resource requirements (vCPU, memory). */
  resources?: ResourceOptions
  /** Networking options (egress allowlist, bandwidth estimates). */
  networking?: NetworkingOptions
  /** Asset delivery options (compression). */
  assets?: AssetOptions
  /** Timeout in milliseconds (default: 30000). */
  timeoutMs?: bigint
  /** Runtime to use (default: "python:3.12"). */
  runtime?: string
  /** Environment variables. */
  env?: Record<string, string>
}
/** Result from a completed job. */
export interface NativeJobResult {
  /** Exit code (0 = success). */
  exitCode: number
  /** Decrypted output data. */
  output: Buffer
  /** Execution duration in milliseconds. */
  durationMs: bigint
  /** Resource usage metrics. */
  metrics: JobMetrics
}
/**
 * Channel keys derived from a payment channel relationship.
 */
export declare class ChannelKeys {
  /** Get the channel master key (32 bytes). */
  masterKey(): Buffer
  /** Get the peer's X25519 public key (32 bytes). */
  peerPublicKey(): Buffer
}
/**
 * An encrypted blob containing all data needed for decryption.
 */
export declare class EncryptedBlob {
  /** Get the format version. */
  get version(): number
  /** Get the ephemeral X25519 public key used for this encryption (32 bytes). */
  get ephemeralPubkey(): Buffer
  /** Get the 192-bit nonce (24 bytes). */
  get nonce(): Buffer
  /** Get the ciphertext with authentication tag. */
  get ciphertext(): Buffer
  /** Serialize the blob to bytes for transmission/storage. */
  toBytes(): Buffer
  /** Deserialize a blob from bytes. */
  static fromBytes(bytes: Buffer): EncryptedBlob
}
/**
 * A native Graphene network client using HTTP transport.
 */
export declare class GrapheneClient {
  /** Create a new Graphene client. */
  static create(config: ClientConfig): Promise<GrapheneClient>
  /** Submit a job to the worker. */
  submitJob(options: JobOptions): Promise<NativeJobResult>
  /** Get the current nonce value. */
  get currentNonce(): bigint
  /** Get the cumulative amount authorized. */
  get totalAuthorized(): bigint
  /** Gracefully shut down the client. */
  shutdown(): Promise<void>
}
