/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'sdk-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.android-arm64.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'sdk-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'sdk-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'sdk-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'sdk-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'sdk-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./sdk-native.darwin-universal.node')
      } else {
        nativeBinding = require('@graphene/sdk-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'sdk-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.darwin-x64.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'sdk-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'sdk-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./sdk-native.freebsd-x64.node')
      } else {
        nativeBinding = require('@graphene/sdk-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sdk-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sdk-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@graphene/sdk-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'sdk-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sdk-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@graphene/sdk-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { EncryptionDirection, ChannelKeys, EncryptedBlob, deriveChannelKeys, encryptJobBlob, decryptJobBlob, PaymentTicket, createPaymentTicket, verifyTicketSignature, validateTicket, blake3Hash, JobStatus, RejectReason, serializeJobRequest, deserializeJobResponse, encodeWireMessage, decodeWireMessage, GrapheneClient } = nativeBinding

module.exports.EncryptionDirection = EncryptionDirection
module.exports.ChannelKeys = ChannelKeys
module.exports.EncryptedBlob = EncryptedBlob
module.exports.deriveChannelKeys = deriveChannelKeys
module.exports.encryptJobBlob = encryptJobBlob
module.exports.decryptJobBlob = decryptJobBlob
module.exports.PaymentTicket = PaymentTicket
module.exports.createPaymentTicket = createPaymentTicket
module.exports.verifyTicketSignature = verifyTicketSignature
module.exports.validateTicket = validateTicket
module.exports.blake3Hash = blake3Hash
module.exports.JobStatus = JobStatus
module.exports.RejectReason = RejectReason
module.exports.serializeJobRequest = serializeJobRequest
module.exports.deserializeJobResponse = deserializeJobResponse
module.exports.encodeWireMessage = encodeWireMessage
module.exports.decodeWireMessage = decodeWireMessage
module.exports.GrapheneClient = GrapheneClient
