# Graphene Network Node OS - Yocto Layer Configuration
# SPDX-License-Identifier: Apache-2.0

# Layer name and priority
BBPATH .= ":${LAYERDIR}"
BBFILES += ""
BBFILE_COLLECTIONS += "meta-graphene"
BBFILE_PATTERN_meta-graphene = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-graphene = "10"

# Layer version
LAYERVERSION_meta-graphene = "1"

# Compatible Yocto releases
LAYERSERIES_COMPAT_meta-graphene = "kirkstone scarthgap"

# Layer dependencies
LAYERDEPENDS_meta-graphene = "core"

# Add recipes
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

# Add classes
BBPATH .= ":${LAYERDIR}/classes"
