# OpenCapsule Network Node OS - Yocto Layer Configuration
# SPDX-License-Identifier: Apache-2.0

# Layer name and priority
BBPATH .= ":${LAYERDIR}"
BBFILES += ""
BBFILE_COLLECTIONS += "meta-opencapsule"
BBFILE_PATTERN_meta-opencapsule = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-opencapsule = "10"

# Layer version
LAYERVERSION_meta-opencapsule = "1"

# Compatible Yocto releases
LAYERSERIES_COMPAT_meta-opencapsule = "kirkstone scarthgap whinlatter"

# Layer dependencies
LAYERDEPENDS_meta-opencapsule = "core"

# Add recipes
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

# Add classes
BBPATH .= ":${LAYERDIR}/classes"
